export const gameConstants = {
  ENTER_PLAYERS_FINISHED: "ENTER_PLAYERS_FINISHED",
  CHANGE_ROUND: "CHANGE_ROUND",
  NEXT_PLAYER: "NEXT_PLAYER",
  NEW_GAME: "NEW_GAME",
  SET_ROUND_WINNER: "SET_ROUND_WINNER",
  ADD_ROUND: "ADD_ROUND",
  FINISH_GAME: "FiNISH_GAME",
  GO_TO_RANKING: "GO_TO_RANKING",
  NEW_MOVE: "NEW_MOVE",
  DELETE_MOVE: "DELETE_MOVE",
  UPDATE_MOVE: "UPDATE_MOVE",
  CANCELL_ROUND: "CANCELL_ROUND"
};
