export const gameConstants = {
  ENTER_PLAYERS_FINISHED: "ENTER_PLAYERS_FINISHED",
  CHANGE_ROUND: "CHANGE_ROUND",
  NEXT_PLAYER: "NEXT_PLAYER",
  NEW_GAME: "NEW_GAME",
  SET_ROUND_WINNER: "SET_ROUND_WINNER",
  ADD_ROUND: "ADD_ROUND"
};
